server:
  port: 9040
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  datasource:
    name: snpt_user
    url: jdbc:mysql://localhost:3306/snpt_user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 134679
  redis:
    host:  118.178.121.175
  rabbitmq:
    host:  47.100.35.57
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
#    ip-address: 118.178.121.175
mybatis:
  mapper-locations: classpath:/Mapper/*.xml
  type-aliases-package: com.wly.entity

